CREATE TABLE ZAPATILLA(
ID NUMERIC(5),
NAME VARCHAR(50),
PRICE FLOAT(5,2),
SIZES NUMERIC(2),
RELEASEDATE DATE,
STOCK BOOLEAN,
CONSTRAINT PK_ZAPATILLA PRIMARY KEY(ID)
);

CREATE TABLE USUARIO(
USERNAME VARCHAR(50),
PASSWORDD VARCHAR(50),
CONSTRAINT PK_USUARIO PRIMARY KEY(USERNAME)
);